name: dockerhub
on:
  workflow_dispatch:
    inputs:
      version:
        description: PROTECTOR4J_VERSION
        required: true
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        build-args: |
          PROTECTOR4J_VERSION=${{ github.event.inputs.version }}
        push: true
        tags: |
          inaccel/protector4j:latest
          inaccel/protector4j:${{ github.event.inputs.version }}
